# version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: maintenance-postgres
    environment:
      POSTGRES_DB: maintenance
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: maintenance-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  backend:
    build: ./backend
    container_name: maintenance-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/maintenance
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data: