spring.datasource.url=jdbc:postgresql://localhost:5432/learning_db
spring.datasource.username=admin_dev
spring.datasource.password=dev_password_root

# --- AGREGAR ESTAS DOS LÍNEAS PARA CORREGIR EL ERROR ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ------------------------------------------------------

# Configuración adicional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Configuraciones de usuario Ucz
spring.application.name=store
