#===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/learning_db
spring.datasource.username=admin_dev
spring.datasource.password=dev_password_root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080
#
# ===============================
# Spring a mostrar cada detalle de la configuración del túnel de audio.
# ===============================
logging.level.org.springframework.web.socket=DEBUG
#
# En tu servidor local Ubuntu, el modelo vive dentro de tu árbol estructurado del Monorepo
vosk.model.path=/home/admin-ia/02_Projects/Github/swworkplace/apps/pm-avisos-voice/model-es